version: '3.1'
services:

  app:
    build:
      context: .
      dockerfile: ./sbin/docker/dev-alpine.dockerfile
    command: run ./bin/launcher/main.go
    volumes:
      - esdata1:/go-money
    environment:
      - ENV=local
    ports:
      - 8001:8080

  postgres:
    build:
      context: .
      dockerfile: ./sbin/docker/psql.dockerfile
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 7001:5432

  manager:
    image: adminer
    restart: always
    ports:
      - 9999:9999
volumes:
  esdata1:
    driver: local
